Debug

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,75 +10,75 @@ jobs:
   build:
     name: Before install
     runs-on: ubuntu-latest
-    services:
-      mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_ROOT_PASSWORD: root
-        ports:
-          - 3306:3306
+#    services:
+#      mysql:
+#        image: mysql:5.7
+#        env:
+#          MYSQL_ROOT_PASSWORD: root
+#        ports:
+#          - 3306:3306
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-      - name: Setup PHP version
-        uses: nanasess/setup-php@v3.0.6
-        with:
-          php-version: '7.4'
-      - name: SSH keys
-        run: |
-          # Make private key available from github secrets.
-          mkdir -p ~/.ssh
-          rm -fv ~/.ssh/id_rsa
-          touch ~/.ssh/id_rsa
-          echo "${{ secrets.CIDRUPALCZPRIVATE }}" >> ~/.ssh/id_rsa
-          eval "$(ssh-agent -s)"
-          chmod 700 ~/.ssh/
-          chmod 600 ~/.ssh/id_rsa
-          ssh-add ~/.ssh/id_rsa
-          # Bypass ~/.ssh/known_host and fix "Host key verification failed.".
-          touch ~/.ssh/config
-          chmod 600 ~/.ssh/config
-          echo "Host *" >> ~/.ssh/config
-          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
-          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
-          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
-      - name: Cache composer
-        uses: actions/cache@v2
-        with:
-          path: |
-            $HOME/.composer/cache
-            vendor
-          key: composer-${{ hashFiles('**/composer.lock') }}
-      - name: Install dependencies
-        run: |
-          sudo composer self-update --1
-          composer validate --no-check-all --ansi
-          composer install --no-suggest
-          echo ${COMPOSER_BIN} >> $GITHUB_PATH
-      - name: Verify MySQL connection from host
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y mysql-client
-          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot -e "select @@hostname;show variables where Variable_name like '%host%';"
-          mysql --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot --protocol=tcp -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'%' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'%';"
-      - name: Install chromedriver
-        run: ${BLT_DIR}/scripts/linux/install-chrome.sh ${COMPOSER_BIN}
-      - name: Configure git
-        run: |
-          git config --global user.name "CI"
-          git config --global user.email "ci@drupal.cz"
-      - name: Run tests
-        run: |
-          blt validate:all --no-interaction || exit 1
-          blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --verbose || exit 1
-          blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose || exit 1
-      - name: Simulate deploy
-        run: |
-          blt artifact:deploy --dry-run --commit-msg "Automated commit by CI for Build ${{ github.run_id}}" --no-interaction --verbose
-          rm -rf deploy
+#      - name: Setup PHP version
+#        uses: nanasess/setup-php@v3.0.6
+#        with:
+#          php-version: '7.4'
+#      - name: SSH keys
+#        run: |
+#          # Make private key available from github secrets.
+#          mkdir -p ~/.ssh
+#          rm -fv ~/.ssh/id_rsa
+#          touch ~/.ssh/id_rsa
+#          echo "${{ secrets.CIDRUPALCZPRIVATE }}" >> ~/.ssh/id_rsa
+#          eval "$(ssh-agent -s)"
+#          chmod 700 ~/.ssh/
+#          chmod 600 ~/.ssh/id_rsa
+#          ssh-add ~/.ssh/id_rsa
+#          # Bypass ~/.ssh/known_host and fix "Host key verification failed.".
+#          touch ~/.ssh/config
+#          chmod 600 ~/.ssh/config
+#          echo "Host *" >> ~/.ssh/config
+#          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
+#          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
+#          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
+#      - name: Cache composer
+#        uses: actions/cache@v2
+#        with:
+#          path: |
+#            $HOME/.composer/cache
+#            vendor
+#          key: composer-${{ hashFiles('**/composer.lock') }}
+#      - name: Install dependencies
+#        run: |
+#          sudo composer self-update --1
+#          composer validate --no-check-all --ansi
+#          composer install --no-suggest
+#          echo ${COMPOSER_BIN} >> $GITHUB_PATH
+#      - name: Verify MySQL connection from host
+#        run: |
+#          sudo apt-get update
+#          sudo apt-get install -y mysql-client
+#          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot -e "select @@hostname;show variables where Variable_name like '%host%';"
+#          mysql --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot --protocol=tcp -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'%' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'%';"
+#      - name: Install chromedriver
+#        run: ${BLT_DIR}/scripts/linux/install-chrome.sh ${COMPOSER_BIN}
+#      - name: Configure git
+#        run: |
+#          git config --global user.name "CI"
+#          git config --global user.email "ci@drupal.cz"
+#      - name: Run tests
+#        run: |
+#          blt validate:all --no-interaction || exit 1
+#          blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --verbose || exit 1
+#          blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose || exit 1
+#      - name: Simulate deploy
+#        run: |
+#          blt artifact:deploy --dry-run --commit-msg "Automated commit by CI for Build ${{ github.run_id}}" --no-interaction --verbose
+#          rm -rf deploy
       - name: Extract branch name
         shell: bash
-        run: echo "::set-output name=branch::$(git branch --show-current)"
+        run: echo "::set-output name=branch:$(git branch --show-current)"
         id: extract_branch
       - name: Debug
         run: |
@@ -86,7 +86,7 @@ jobs:
           if [ ${{ steps.extract_branch.outputs.branch }} == 'master' || ${{ steps.extract_branch.outputs.branch }} == 'develop' ]; then
             echo "We want to do deploy"
           fi
-      - name: Run deploy on master and develop
-        if: ${{ steps.extract_branch.outputs.branch }} == 'master' || ${{ steps.extract_branch.outputs.branch }} == 'develop'
-        run: |
-          blt artifact:deploy --commit-msg "Automated commit by CI for Build ${{ github.run_id}}" --branch "${{ steps.extract_branch.outputs.branch }}-build" --no-interaction --verbose
+#      - name: Run deploy on master and develop
+#        if: ${{ steps.extract_branch.outputs.branch }} == 'master' || ${{ steps.extract_branch.outputs.branch }} == 'develop'
+#        run: |
+#          blt artifact:deploy --commit-msg "Automated commit by CI for Build ${{ github.run_id}}" --branch "${{ steps.extract_branch.outputs.branch }}-build" --no-interaction --verbose
